#!/bin/bash
# Install the forcecalls endpoint: baresip, auto-answering, root-owned, with a watchdog daemon that
# re-bootstraps it if the agent is booted out.
#
#   sudo ./install.sh                  # asks only for the SIP password
#   sudo SIP_PASS=… ./install.sh       # fully non-interactive
#
# RUN THIS WHILE YOU STILL HAVE SUDO. Once admin is revoked you can't install it, and without it a
# forced call reaches the other person and then has nothing to bridge to.
set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$APP_DIR/../../scripts/install-lib.sh"
dl_require_root

USER_NAME="$(dl_user)"
USER_UID="$(id -u "$USER_NAME")"
CREDS="/Library/Application Support/Forcecalls/creds.json"
AGENT_LABEL=com.minh.forcecalls.endpoint
WD_LABEL=com.minh.forcecalls.endpoint-watchdog
cd "$APP_DIR"

# ── identity: reuse what the main installer already stored ───────────────────────────────────────
# creds.json holds `endpoint: sip:user@space.sip.signalwire.com`, so the username and domain are
# already known — only the password was never stored (the daemon never needs it; baresip does).
if [ -n "${SIP_USER:-}" ] && [ -n "${SIP_DOMAIN:-}" ]; then
    :
elif [ -f "$CREDS" ]; then
    EP="$(/usr/bin/python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["endpoint"])' "$CREDS")"
    EP="${EP#sip:}"
    SIP_USER="${EP%%@*}"
    SIP_DOMAIN="${EP##*@}"
    dl_ok "endpoint from creds.json: $SIP_USER@$SIP_DOMAIN"
else
    echo "✗ no $CREDS — run the main installer first:  sudo ../install.sh"
    echo "  (or pass SIP_USER= and SIP_DOMAIN= explicitly)"; exit 1
fi

if [ -z "${SIP_PASS:-}" ]; then
    if [ -t 0 ]; then
        read -r -s -p "  SIP password for $SIP_USER@$SIP_DOMAIN: " SIP_PASS; echo
    else
        echo "✗ no SIP_PASS and no terminal to prompt from."
        echo "  sudo SIP_PASS=… ./install.sh"; echo "  nothing was installed."; exit 1
    fi
fi
[ -n "$SIP_PASS" ] || { echo "✗ SIP password can't be empty"; exit 1; }

# ── baresip ──────────────────────────────────────────────────────────────────────────────────────
# Installed as the user: Homebrew refuses to run as root, and it must land in the user's prefix.
if ! sudo -u "$USER_NAME" command -v baresip >/dev/null 2>&1; then
    echo "▸ installing baresip via Homebrew (as $USER_NAME)"
    sudo -u "$USER_NAME" brew install baresip >/dev/null || { echo "✗ brew install baresip failed"; exit 1; }
fi
BARESIP_BIN="$(sudo -u "$USER_NAME" command -v baresip)"
BREW_PREFIX="$(sudo -u "$USER_NAME" brew --prefix baresip 2>/dev/null || echo /opt/homebrew)"
MODULE_PATH="$BREW_PREFIX/lib/baresip/modules"
[ -d "$MODULE_PATH" ] || MODULE_PATH="$(dirname "$(dirname "$BARESIP_BIN")")/lib/baresip/modules"
[ -d "$MODULE_PATH" ] || { echo "✗ can't find baresip modules (looked in $MODULE_PATH)"; exit 1; }
dl_ok "baresip $BARESIP_BIN  (modules: $MODULE_PATH)"

# ── config ───────────────────────────────────────────────────────────────────────────────────────
echo "▸ writing /etc/baresip"
mkdir -p /etc/baresip /usr/local/libexec
sed "s#^module_path .*#module_path            $MODULE_PATH#" config > /etc/baresip/config
# answermode=auto is the whole point: the far end has already answered by the time we're dialled,
# so there is nothing to decide. 0600 so you can't read the password back out.
umask 077
cat > /etc/baresip/accounts <<EOF
# generated by forcecalls/endpoint/install.sh — do not edit by hand
<sip:$SIP_USER@$SIP_DOMAIN>;auth_user=$SIP_USER;auth_pass=$SIP_PASS;answermode=auto;regint=60;medianat=ice;stunserver=stun:stun.l.google.com:19302
EOF
umask 022

install -m 0755 -o root -g wheel watchdog.sh /usr/local/libexec/forcecalls-endpoint-watchdog.sh

# ── launchd ──────────────────────────────────────────────────────────────────────────────────────
echo "▸ installing launchd jobs"
sed "s#/opt/homebrew/bin/baresip#$BARESIP_BIN#" "$AGENT_LABEL.plist" > "/Library/LaunchAgents/$AGENT_LABEL.plist"
cp "$WD_LABEL.plist" "/Library/LaunchDaemons/$WD_LABEL.plist"

chown -R root:wheel /etc/baresip
chown root:wheel "/Library/LaunchAgents/$AGENT_LABEL.plist" "/Library/LaunchDaemons/$WD_LABEL.plist"
chmod 644 /etc/baresip/config "/Library/LaunchAgents/$AGENT_LABEL.plist" "/Library/LaunchDaemons/$WD_LABEL.plist"
chmod 600 /etc/baresip/accounts
touch /var/log/baresip.log && chown "$USER_NAME" /var/log/baresip.log

launchctl bootout "gui/$USER_UID/$AGENT_LABEL" 2>/dev/null || true
launchctl bootout "system/$WD_LABEL" 2>/dev/null || true
sleep 1
launchctl bootstrap "gui/$USER_UID" "/Library/LaunchAgents/$AGENT_LABEL.plist" 2>/dev/null \
    || launchctl kickstart -k "gui/$USER_UID/$AGENT_LABEL" 2>/dev/null || true
launchctl bootstrap system "/Library/LaunchDaemons/$WD_LABEL.plist" 2>/dev/null \
    || launchctl kickstart -k "system/$WD_LABEL" 2>/dev/null || true

# ── verify ───────────────────────────────────────────────────────────────────────────────────────
# Registration is the one thing that silently ruins everything: without it SignalWire has no address
# to ring and the call dies after the far end picks up. Check it here rather than at 8:45 PM.
echo "▸ waiting for SIP registration…"
OK=no
for _ in $(seq 15); do
    sleep 1
    if grep -qi "200 OK\|registered" /var/log/baresip.log 2>/dev/null; then OK=yes; break; fi
done
if [ "$OK" = yes ]; then
    dl_ok "registered as $SIP_USER@$SIP_DOMAIN"
else
    dl_warn "no registration seen yet — check: tail -20 /var/log/baresip.log"
    dl_warn "a wrong SIP password shows up here as a 401. re-run with the right one."
fi

echo
echo "✓ endpoint installed."
echo "  verify it survives being killed (do this BEFORE you drop sudo):"
echo "    pkill baresip && sleep 3 && pgrep baresip                       # KeepAlive brings it back"
echo "    launchctl bootout gui/$USER_UID/$AGENT_LABEL"
echo "    sleep 15 && pgrep baresip                                        # watchdog re-bootstraps it"
echo
echo "  then rehearse the real thing:  forcecalls testcall +1YOUROWNCELL"
